### ISSUE TITLE
Undo after user swipe

### ISSUE THREAD

**Issue by Skipperlla** [Skipperlla/rn-tinder-card#3]

**Comment by Skipperlla** [comment]
@AmirBraham hi this feature is a little long due to my full time job but i plan to add this feature over the weekend

**Comment by AmirBraham** [comment]
Thanks ! Do you have any suggestions on the implementation part ? Maybe I can make a quick PR

**Comment by Skipperlla** [comment]
@AmirBraham I couldn't create a todo because I don't have time right now, but I'll let you know when I do.

**Comment by Skipperlla** [comment]
for those who see this comment again friends, unfortunately I can not look at pr for a long time because I am very busy, I apologize for being late

**Comment by PEZO19** [comment]
@AmirBraham It is not documented yet, but it does seem to work.
@Skipperlla Thanks for your lib, it's awesome!

```js
const cardRef = useRef(null);

const handleSwipeBack = () => {
  cardRef.current?.swipeBack();
}
  
<TinderCard ref={cardRef}
...
</TinderCard>
  
<Button title="Swipe Back" onPress={handleSwipeBack} />
```

**Comment by Skipperlla** [comment]
@PEZO19 I have a lot of busy due to my job, so this development has been open for a while, I plan to finish it this week and add more cool features, just stay tuned.

**Comment by devreeda** [comment]
Hey, in the meantime, I'll show you how I implemented this quickly:
```typescript
const cardPosition = useRef(new Animated.ValueXY()).current;

const { width } = Dimensions.get('window');

const handleSwipeBack = () => {
            // Determine the direction to animate from
            const lastSwipedCard = swipedCards[swipedCards.length - 1];
            const fromValue = lastSwipedCard.leftSwipe ? -width : width;
            cardPosition.setValue({ x: fromValue, y: 0 });

            Animated.spring(cardPosition, {
                toValue: { x: 0, y: 0 },
                useNativeDriver: true,
            }).start(() => {
                // Optional: callback after animation completes
            });
        }
    };
    return (
                    <Animated.View style={{ transform: cardPosition.getTranslateTransform() }}>
                        <YourCardComponent />
                    </Animated.View>
    )

```

`swipedCards` being an array storing the swiped cards objects, more specifically whether they have been swiped left or right. I am no expert in animation but hope it helped.

**Comment by Skipperlla** [comment]
@devreeda I realize that I've been neglecting this place a lot because of my own project, if I can find the time I will close this pr. It's my first open source project and I'm sorry I haven't been able to maintain it properly.

**Comment by Skipperlla** [comment]
@devreeda if you write with `reanimated` as an extra I can review and merge

**Comment by PEZO19** [comment]
May I ask why this isn't enough for people? :)

https://github.com/Skipperlla/rn-tinder-card/blob/20ac1ae3b6b12bf14fb0253bf610a1f6cafd782a/src/CardItem.tsx#L240-L247

**Comment by 0xPasho** [comment]
Ref works fine, I've been using it to undo a swipe.
Maybe this could help some time debugging and help someone; For those who are dynamicaly only rendering a split amount of elements from cards, and you can't use the index as ref to get it back to it, you can use your element id in the ref like this:
```typescript
const cardRefs = useRef<{ [prop: string]: CardItemHandle }>({});
const handleSwipe = (type: 'left' | 'right') => {
  if(type === 'left') {
    cardRefs.current[card.id].swipeBack();
    return;
  }
}
return (
  <TinderCard 
    handleSwipe('left')
    handleSwipe('right')
    ref={(el) => (cardRefs.current[card.id] = el!)}
  >
    {renderCard(card, index)}
  </TinderCard>
);
```
